### ISSUE TITLE
Using Flow with custom algorithm

### ISSUE THREAD

**Issue by mynkpl1998** [berkeleyflow/flow#7]
Is there any way to use the Flow with any other algorithms other than which are provided. I could not able to find an `env.step()` like function which takes action and observation/state and updates the environment and return next state, reward

**Comment by eugenevinitsky** [comment]
Hi! Sorry for the delay.
So we do a slight change to the normal environment. We have our env.step() function hidden in our Env class which is in the base_env.py file. Rather than the normal subclass of GymEnv you need to subclass Env and fill out the following methods:
         -  action_space
         - observation_space
         - apply_rl_action
         - get_state
         - compute_reward
Let me know if that clears it up for you. Additionally, if you look in our tutorials, specifically tutorial_06_environments, that should have more details.

**Comment by mynkpl1998** [comment]
Thank you for the clarification. Closing the issue.
